### ISSUE TITLE
Can't install httpie. Fails on httpsig_cffi. 

### ISSUE THREAD

**Issue by labeneator** [manuthu/httpie-http-signatures#1]
Perhaps httpsig_cffi needs to be declared in setup.py?

```
 ❯ http --version
0.9.9

 ❯ pip install -U httpie-httpsig-auth 
Collecting httpie-httpsig-auth
  Using cached httpie-httpsig-auth-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/lmwangi/pip-build-_sAGel/httpie-httpsig-auth/setup.py", line 1, in <module>
        import httpie_httpsig_auth
      File "httpie_httpsig_auth.py", line 6, in <module>
        import httpsig_cffi.sign
    ImportError: No module named httpsig_cffi.sign

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/lmwangi/pip-build-_sAGel/httpie-httpsig-auth/
```

**Comment by labeneator** [comment]
Yup.  Preinstalling httpsig_cffi allows the package to be installed

```
pip install httpsig_cffi
pip install -U httpie-httpsig-auth
```

**Comment by manuthu** [comment]
The requirement appears to be in the `setup.py` 

```
(test) ➜  ~ pip install httpie-httpsig-auth
Collecting httpie-httpsig-auth
Collecting requests>=2.14.2 (from httpie-httpsig-auth)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting six>=1.10.0 (from httpie-httpsig-auth)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting httpsig-cffi>=15.0.0 (from httpie-httpsig-auth)
  Using cached httpsig_cffi-15.0.0-py2.py3-none-any.whl
Collecting httpie>=0.7.0 (from httpie-httpsig-auth)
  Using cached httpie-0.9.9-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>=2.14.2->httpie-httpsig-auth)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.14.2->httpie-httpsig-auth)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.14.2->httpie-httpsig-auth)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.14.2->httpie-httpsig-auth)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting cryptography (from httpsig-cffi>=15.0.0->httpie-httpsig-auth)
  Using cached cryptography-2.0.3-cp27-cp27m-macosx_10_6_intel.whl
Collecting Pygments>=2.1.3 (from httpie>=0.7.0->httpie-httpsig-auth)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting ipaddress (from cryptography->httpsig-cffi>=15.0.0->httpie-httpsig-auth)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography->httpsig-cffi>=15.0.0->httpie-httpsig-auth)
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting enum34 (from cryptography->httpsig-cffi>=15.0.0->httpie-httpsig-auth)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting cffi>=1.7 (from cryptography->httpsig-cffi>=15.0.0->httpie-httpsig-auth)
  Using cached cffi-1.10.0-cp27-cp27m-macosx_10_6_intel.whl
Collecting pycparser (from cffi>=1.7->cryptography->httpsig-cffi>=15.0.0->httpie-httpsig-auth)
Installing collected packages: idna, urllib3, certifi, chardet, requests, six, ipaddress, asn1crypto, enum34, pycparser, cffi, cryptography, httpsig-cffi, Pygments, httpie, httpie-httpsig-auth
Successfully installed Pygments-2.2.0 asn1crypto-0.22.0 certifi-2017.7.27.1 cffi-1.10.0 chardet-3.0.4 cryptography-2.0.3 enum34-1.1.6 httpie-0.9.9 httpie-httpsig-auth-0.1.0 httpsig-cffi-15.0.0 idna-2.6 ipaddress-1.0.18 pycparser-2.18 requests-2.18.4 six-1.10.0 urllib3-1.22

```

**Comment by labeneator** [comment]
So why does it fail in my use case? Can you try on a box w/out httpie preinstalled?

**Comment by manuthu** [comment]
Fixed and changes made upstream
